MODEL:
  NAME: 'resnet50'
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/jongphago/.torch/models/resnet50.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: 'aihub_kaist'
  ROOT_DIR: './data'
  # 테스트용 훈련 폴더: 'bounding_box_train_1', 'bounding_box_train_2', 'bounding_box_train_3' 중 선택
  TRAIN_FOLDER: 'bounding_box_train_1'
  QUERY_FOLDER: 'query'
  GALLERY_FOLDER: 'bounding_box_test'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 5  # 빠른 테스트를 위한 짧은 학습
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 32  # 작은 배치 크기 (GPU 메모리 절약)

  STEPS: [3]  # 3 에포크에서 학습률 감소
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 5  # 2 에포크마다 체크포인트 저장
  LOG_PERIOD: 10  # 10 배치마다 로그 출력
  EVAL_PERIOD: 1  # 매 에포크마다 평가

TEST:
  IMS_PER_BATCH: 64  # 테스트 배치 크기
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "./log/test_aihub_kaist"

WANDB:
  ENABLE: True
  PROJECT: "reid-aihub-kaist-test"
  ENTITY: ""
  NAME: ""
  TAGS: ["test", "aihub", "kaist", "quick-test"]
  SYNC_TENSORBOARD: False
  SAVE_CODE: False

